mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
# from django.views.generic.base import TemplateView
from mysite.views import DashboardView


urlpatterns = [
    # path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # path('dashboard/', TemplateView.as_view(template_name='admin/home.html'), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),

    path('users/', include('users.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('change-password/', auth_views.LoginView.as_view()),
    
]
admin.site.site_header = 'Admin Dashboard'

polls/urls.py
from django.urls import path

from polls.views import IndexView, DetailView, ResultsView
from . import views

app_name = 'polls'

urlpatterns = [
    # ex: /polls/
    # path('', views.index, name='index'),
    path('', IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', detail, name='detail'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    # path('<int:question_id>/results/', results, name='results'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

users/urls.py
from django.urls import path
from users.views import IndexView, CreateView, UpdateView, DetailView, DeleteView
from django.contrib.auth.decorators import login_required

app_name = 'users'

urlpatterns = [
    path('', login_required(IndexView.as_view()), name='index'),
    path('create', login_required(CreateView.as_view()), name='create'),
    path('<int:pk>/edit', login_required(UpdateView.as_view()), name='edit'),
    path('<int:pk>', login_required(DetailView.as_view()), name='show'),
    path('<int:pk>/delete', login_required(DeleteView.as_view()), name='delete'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

users/models.py
from django.db import models


# Create your models here.

mysite/views.py
from django.views import generic
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
# from django.shortcuts import render

# @login_required
# @permission_required('polls.can_vote')
# def index_view(request):
#     return render(request, 'admin/home.html', {})

class DashboardView(LoginRequiredMixin, TemplateView):
    # permission_required = 'polls.can_vote'
    login_url = '/login/'
    template_name = "admin/home.html"

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from pprint import pprint
from .models import Choice, Question
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    # def get_queryset(self):
    #     """Return the last five published questions."""
    #     return Question.objects.order_by('-pub_date')[:5]
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

users/views.py
from django.shortcuts import render
from django.views import generic
# from .models import User
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import transaction
from django.http import HttpResponseRedirect
from django.contrib.auth.hashers import make_password
from django.shortcuts import get_object_or_404
from django.http import Http404

# Create your views here.
class IndexView(
    generic.ListView):
    template_name = 'users/index.html'
    login_url = '/login/'
    context_object_name = 'latest_user_list'

    def get_queryset(self):
        """ Return the last fice users. """
        return User.objects.order_by('-date_joined')[:5]


class CreateView(
    generic.edit.CreateView):
    template_name = 'users/create.html'
    model = User
    success_message = 'New new user has been created.'

    fields = ['first_name', 'last_name', 'username', 'email', 'password']

    def form_valid(self, form):
        password = make_password(form.cleaned_data.get('password'))
        form.instance.password = password
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('users:index')


class UpdateView(
    generic.edit.UpdateView):
    template_name = 'users/edit.html'
    model = User
    fields = ['first_name', 'last_name', 'username', 'email']

    def get_object(self, *args, **kwargs):
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        return user
    
    def get_success_url(self):
        return reverse('users:index')
        # return reverse('users:edit', kwargs={'pk': self.object.pk})


class DetailView(
    generic.DetailView):
    template_name = 'users/show.html'
    model = User


class DeleteView(
    generic.DeleteView):
    # template_name = ''
    model = User
    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        user = get_object_or_404(User, pk=self.kwargs['pk'])
        # obj = super(DeleteView, self).get_object()
        # if not obj.owner == self.request.user:
        #     raise Http404
        return user

    def get_success_url(self):
        return reverse('users:index')

    

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/layouts/admin/base.html
<!doctype html>

{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Django 2.2</title>

    {% include "layouts/admin/partials/styles.html" %}
  </head>

  <body>
    {% include "layouts/admin/partials/header.html" %}

    <div class="container-fluid">
      <div class="row">
      {% include "layouts/admin/partials/sidebar.html" %}
      {% block content %}
      {% endblock %}
      </div>
    </div>
    {% include "layouts/admin/partials/scripts.html" %}
  </body>
</html>

templates/layouts/admin/partials/header.html
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Django 2.2</a>
    <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{%  url 'logout' %}">Sign out</a>
        </li>
    </ul>
</nav>

templates/layouts/admin/partials/scripts.html
{% load static %}

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
</script>
<script>
    window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')
</script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

<!-- Graphs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            datasets: [{
                data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#007bff'
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: false
                    }
                }]
            },
            legend: {
                display: false,
            }
        }
    });
</script>

templates/layouts/admin/partials/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'dashboard' %}">
                    <span data-feather="home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file"></span>
                    Orders
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="shopping-cart"></span>
                    Products
                </a>
            </li> {% endcomment %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:index' %}">
                    <span data-feather="users"></span>
                    Users
                </a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="bar-chart-2"></span>
                    Reports
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="layers"></span>
                    Integrations
                </a>
            </li> {% endcomment %}
        </ul>

        {% comment %} <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Saved reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
            </a>
        </h6>
        <ul class="nav flex-column mb-2">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Current month
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Last quarter
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Social engagement
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <span data-feather="file-text"></span>
                    Year-end sale
                </a>
            </li>
        </ul> {% endcomment %}
    </div>
</nav>

templates/layouts/admin/partials/styles.html
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard.css' %}" rel="stylesheet">

users/templates/users/create.html
{% extends  'layouts/admin/base.html' %}
{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
	<form id="user-create" method="post">
		{% csrf_token %}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>First Name</label>
				<input type="text" name="first_name" class="form-control" placeholder="First Name">
			</div>
			<div class="form-group col-md-6">
				<label>Last Name</label>
				<input type="text" name="last_name" class="form-control" placeholder="Last Name">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Username</label>
				<input type="text" name="username" class="form-control" placeholder="Username">
			</div>
			<div class="form-group col-md-6">
				<label>Email</label>
				<input type="email" name="email" class="form-control"placeholder="Email">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Password</label>
				<input type="password" name="password" class="form-control" placeholder="Password">
			</div>
			<div class="form-group col-md-6">
				<label>Confirm Password</label>
				<input type="password" name="confirm_password" class="form-control"placeholder="Confirm Password">
			</div>
		</div>
		<a href="{% url 'users:index' %}" class="btn btn-secondary">Cancel</a>
		<button type="submit" class="btn btn-success">Create</button>
</main>
{% endblock content %}

users/templates/users/edit.html
{% extends  'layouts/admin/base.html' %}
{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
	<form id="user-update" method="POST">
		{% csrf_token %}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>First Name</label>
				<input type="text" name="first_name" class="form-control" value="{{ user.first_name }}" placeholder="First Name">
			</div>
			<div class="form-group col-md-6">
				<label>Last Name</label>
				<input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" placeholder="Last Name">
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Username</label>
				<input type="text" name="username" class="form-control" value="{{ user.username }}" placeholder="Username">
			</div>
			<div class="form-group col-md-6">
				<label>Email</label>
				<input type="email" name="email" class="form-control" value="{{ user.email }}" placeholder="Email">
			</div>
		</div>
		<a href="{% url 'users:index' %}" class="btn btn-secondary">Cancel</a>
		<button type="submit" class="btn btn-primary">Update</button>
</main>
{% endblock content %}

users/templates/users/index.html
{% extends  'layouts/admin/base.html' %}
{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
    <h1 class="h2">Users</h1>
    <div class="btn-group mr-2">
      <a href="{% url 'users:create' %}" class="btn btn-sm btn-outline-success">Create</a>
    </div>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
          <th>Username</th>
          <th>Joined At</th>
          <td>#</td>
        </tr>
      </thead>
      <tbody>
        {% for user in latest_user_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ user.first_name }} {{ user.last_name }}</td>
          <td>{{ user.email }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.date_joined }}</td>
          <td>
            <div class="dropdown show">
              <a class="btn btn-sm btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Actions
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="{% url 'users:show' user.id %}">View</a>
                <a class="dropdown-item" href="{% url 'users:edit' user.id %}">Edit</a>
                <form action="{% url "users:delete" user.id %}" method="post">
                  {% csrf_token %}
                  <button class="dropdown-item" onclick="return confirm('Are you sure?');">Delete</button>
                </form>
              </div>
            </div>
          </td>

        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
</main>
{% endblock content %}

users/templates/users/show.html
{% extends  'layouts/admin/base.html' %}
{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
	<form id="user-update" method="POST">
		{% csrf_token %}
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>First Name</label>
				<input type="text" name="first_name" class="form-control" value="{{ user.first_name }}" readonly>
			</div>
			<div class="form-group col-md-6">
				<label>Last Name</label>
				<input type="text" name="last_name" class="form-control" value="{{ user.last_name }}" readonly>
			</div>
		</div>
		<div class="form-row">
			<div class="form-group col-md-6">
				<label>Username</label>
				<input type="text" name="username" class="form-control" value="{{ user.username }}" readonly>
			</div>
			<div class="form-group col-md-6">
				<label>Email</label>
				<input type="email" name="email" class="form-control" value="{{ user.email }}" readonly>
			</div>
		</div>
		<a href="{% url 'users:index' %}" class="btn btn-secondary">Cancel</a>
</main>
{% endblock content %}